# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-12-13 03:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ApiTest', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Case',
            new_name='ApiCase',
        ),
    ]
