# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-12-14 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiTest', '0003_auto_20191213_1618'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=150, verbose_name='区域')),
                ('classification', models.CharField(max_length=150, verbose_name='分类')),
                ('title', models.CharField(max_length=150, verbose_name='标题')),
                ('icon', models.CharField(max_length=150, verbose_name='图标')),
                ('href', models.CharField(max_length=150, verbose_name='链接')),
                ('spread', models.BooleanField(default=False, verbose_name='默认不展开')),
            ],
        ),
    ]
