# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-12-14 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiTest', '0004_automenu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automenu',
            name='icon',
            field=models.CharField(default='&#xe674', max_length=150, verbose_name='图标'),
        ),
    ]
