# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-12-15 05:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ApiTest', '0007_auto_20191215_1335'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='singleapi',
            options={'verbose_name': '单一接口', 'verbose_name_plural': '单一接口管理'},
        ),
    ]
