# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-12-15 06:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ApiTest', '0008_auto_20191215_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automenu',
            name='classification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApiTest.LeftMenu', verbose_name='所属分类'),
        ),
    ]
