# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-12-15 06:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ApiTest', '0009_auto_20191215_1409'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='automenu',
        #     name='classification',
        # ),
        migrations.DeleteModel(
            name='AutoMenu',
        ),
    ]
