# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-12-15 11:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiTest', '0011_childmenu'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemRole',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=150, verbose_name='角色')),
                ('username', models.CharField(max_length=250, verbose_name='用户名')),
                ('password', models.CharField(max_length=250, verbose_name='密码')),
                ('system', models.CharField(max_length=150, verbose_name='所属系统')),
                ('token', models.CharField(max_length=250, verbose_name='令牌信息')),
            ],
            options={
                'verbose_name': '系统角色',
                'verbose_name_plural': '系统角色管理',
            },
        ),
    ]
