# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-12-15 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiTest', '0012_systemrole'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singleapi',
            name='body',
            field=models.TextField(blank=True, null=True, verbose_name='请求体内容'),
        ),
        migrations.AlterField(
            model_name='singleapi',
            name='duration',
            field=models.FloatField(blank=True, null=True, verbose_name='响应时长'),
        ),
        migrations.AlterField(
            model_name='singleapi',
            name='exceptres',
            field=models.TextField(blank=True, null=True, verbose_name='期望结果'),
        ),
        migrations.AlterField(
            model_name='singleapi',
            name='head',
            field=models.CharField(max_length=200, null=True, verbose_name='负责人'),
        ),
        migrations.AlterField(
            model_name='singleapi',
            name='header',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='请求头'),
        ),
        migrations.AlterField(
            model_name='singleapi',
            name='params',
            field=models.TextField(blank=True, null=True, verbose_name='请求参数'),
        ),
        migrations.AlterField(
            model_name='singleapi',
            name='result',
            field=models.TextField(blank=True, null=True, verbose_name='执行结果'),
        ),
        migrations.AlterField(
            model_name='singleapi',
            name='sortid',
            field=models.IntegerField(blank=True, verbose_name='排序号'),
        ),
        migrations.AlterField(
            model_name='singleapi',
            name='system',
            field=models.CharField(max_length=50, verbose_name='所属系统'),
        ),
        migrations.AlterField(
            model_name='systemrole',
            name='token',
            field=models.CharField(max_length=250, null=True, verbose_name='令牌信息'),
        ),
    ]
