# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-12-15 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiTest', '0013_auto_20191215_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemrole',
            name='token',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='令牌信息'),
        ),
    ]
