# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-12-15 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiTest', '0014_auto_20191215_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singleapi',
            name='sortid',
            field=models.IntegerField(blank=True, null=True, verbose_name='排序号'),
        ),
    ]
