# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-12-16 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiTest', '0015_auto_20191215_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemrole',
            name='identity',
            field=models.CharField(default='sysadmin', max_length=100, verbose_name='角色英文名'),
            preserve_default=False,
        ),
    ]
