# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-12-19 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiTest', '0016_systemrole_identity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('logo', models.CharField(max_length=250, verbose_name='网站logo')),
                ('websites', models.CharField(max_length=250, verbose_name='网站名称')),
                ('url', models.CharField(max_length=250, verbose_name='网址')),
            ],
            options={
                'verbose_name_plural': '网站名称',
            },
        ),
        migrations.CreateModel(
            name='Testurl',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('logo', models.CharField(max_length=250, verbose_name='网站logo')),
                ('websites', models.CharField(max_length=250, verbose_name='网站名称')),
                ('url', models.CharField(max_length=250, verbose_name='网址')),
                ('apidocument', models.CharField(max_length=250, verbose_name='接口文档')),
            ],
            options={
                'verbose_name_plural': '网站名称',
            },
        ),
    ]
