# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-12-26 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiTest', '0017_link_testurl'),
    ]

    operations = [
        migrations.CreateModel(
            name='Processapi',
            fields=[
                ('caseid', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('casename', models.CharField(max_length=100, verbose_name='用例名称')),
                ('identity', models.CharField(max_length=50, verbose_name='用户身份')),
                ('url', models.CharField(max_length=550, verbose_name='访问路径')),
                ('method', models.CharField(max_length=20, verbose_name='请求方式')),
                ('header', models.CharField(blank=True, max_length=200, null=True, verbose_name='请求头')),
                ('params', models.TextField(blank=True, null=True, verbose_name='请求参数')),
                ('body', models.TextField(blank=True, null=True, verbose_name='请求体内容')),
                ('exceptres', models.CharField(max_length=250, null=True, verbose_name='期望结果')),
                ('result', models.TextField(null=True, verbose_name='执行结果')),
                ('belong', models.CharField(max_length=50, verbose_name='所属模块')),
                ('isprocess', models.CharField(max_length=20, null=True, verbose_name='是否有依赖')),
                ('depend_id', models.CharField(max_length=20, null=True, verbose_name='依赖的caseID')),
                ('depend_key', models.CharField(max_length=500, null=True, verbose_name='依赖的key')),
                ('replace_key', models.CharField(max_length=500, null=True, verbose_name='替换的key')),
                ('replace_position', models.CharField(default='params', max_length=50, verbose_name='替换的内容区域')),
                ('sortid', models.IntegerField(default=1, verbose_name='排序号')),
                ('system', models.CharField(max_length=50, verbose_name='所属系统')),
                ('duration', models.FloatField(null=True, verbose_name='响应时长')),
            ],
            options={
                'verbose_name_plural': '接口流程测试',
            },
        ),
        migrations.AlterModelOptions(
            name='link',
            options={'verbose_name_plural': '友情链接'},
        ),
        migrations.AlterModelOptions(
            name='testurl',
            options={'verbose_name_plural': '测试网址'},
        ),
    ]
