# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-12-26 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiTest', '0018_auto_20191226_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='processapi',
            name='head',
            field=models.CharField(max_length=200, null=True, verbose_name='负责人'),
        ),
    ]
