# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-12-26 15:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ApiTest', '0019_processapi_head'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='processapi',
            options={'verbose_name_plural': '接口流程管理'},
        ),
        migrations.AlterField(
            model_name='processapi',
            name='belong',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApiTest.ChildMenu', verbose_name='所属模块'),
        ),
        migrations.AlterField(
            model_name='processapi',
            name='isprocess',
            field=models.CharField(default=False, max_length=20, verbose_name='是否有依赖'),
        ),
    ]
