# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-12-29 06:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiTest', '0020_auto_20191226_2334'),
    ]

    operations = [
        migrations.AddField(
            model_name='childmenu',
            name='nav',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='左侧导航的键'),
        ),
    ]
