# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-12-29 06:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiTest', '0021_childmenu_nav'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processapi',
            name='depend_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='依赖的caseID'),
        ),
        migrations.AlterField(
            model_name='processapi',
            name='depend_key',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='依赖的key'),
        ),
        migrations.AlterField(
            model_name='processapi',
            name='duration',
            field=models.FloatField(blank=True, null=True, verbose_name='响应时长'),
        ),
        migrations.AlterField(
            model_name='processapi',
            name='exceptres',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='期望结果'),
        ),
        migrations.AlterField(
            model_name='processapi',
            name='head',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='负责人'),
        ),
        migrations.AlterField(
            model_name='processapi',
            name='replace_key',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='替换的key'),
        ),
        migrations.AlterField(
            model_name='processapi',
            name='result',
            field=models.TextField(blank=True, null=True, verbose_name='执行结果'),
        ),
    ]
