# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-12-29 06:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiTest', '0022_auto_20191229_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processapi',
            name='replace_position',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='替换的内容区域'),
        ),
    ]
