# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-12-29 08:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ApiTest', '0023_auto_20191229_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processapi',
            name='belong',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='childmenu_processapi', to='ApiTest.ChildMenu', verbose_name='所属模块'),
        ),
    ]
