# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-01-08 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiTest', '0025_auto_20191229_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemrole',
            name='ip',
            field=models.CharField(default='amberdata.cn', max_length=200, verbose_name='IP地址'),
            preserve_default=False,
        ),
    ]
