# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-03-07 05:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ApiTest', '0028_auto_20200117_2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='SingleApiChild',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter_field', models.CharField(max_length=100, verbose_name='字段名')),
                ('parameter_that', models.CharField(max_length=100, verbose_name='参数说明')),
                ('area', models.IntegerField(choices=[(1, 'Query'), (2, 'Body')], default=1, verbose_name='参数区域')),
                ('isMust', models.BooleanField(default=True, verbose_name='是否必填')),
                ('sample', models.CharField(max_length=999, verbose_name='示例')),
                ('parent_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ApiTest.SingleApi', verbose_name='父id')),
            ],
        ),
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField(max_length=128, verbose_name='操作时间')),
                ('type', models.CharField(max_length=50, verbose_name='操作类型')),
                ('operationObject', models.CharField(max_length=50, verbose_name='操作对象')),
                ('user', models.CharField(max_length=50, verbose_name='操作人')),
                ('description', models.CharField(blank=True, max_length=1024, null=True, verbose_name='描述')),
            ],
            options={
                'verbose_name': '操作日志',
                'verbose_name_plural': '操作日志',
            },
        ),
        migrations.AlterField(
            model_name='processapi',
            name='sortid',
            field=models.IntegerField(blank=True, null=True, verbose_name='排序号'),
        ),
    ]
