# Generated by Django 3.0.3 on 2020-05-19 11:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ApiTest', '0030_auto_20200307_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locustapi',
            name='caseid',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='singleapi',
            name='caseid',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, default='无', max_length=11, verbose_name='手机号')),
                ('openId', models.CharField(default=0, max_length=50, verbose_name='唯一标识')),
                ('unionid', models.CharField(default=0, max_length=50, verbose_name='企业内唯一标识')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
        ),
    ]
