# Generated by Django 3.0.5 on 2020-05-24 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ApiTest', '0031_auto_20200519_1904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemrole',
            name='identity',
        ),
    ]
