# Generated by Django 3.0.3 on 2020-05-28 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ApiTest', '0032_remove_systemrole_identity'),
    ]

    operations = [
        migrations.CreateModel(
            name='FunctionCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=100, verbose_name='所属区域')),
                ('function_model', models.CharField(max_length=100, verbose_name='功能模块')),
                ('function_point', models.CharField(max_length=50, verbose_name='功能点')),
                ('casename', models.CharField(max_length=100, verbose_name='用例名称')),
                ('premise_condition', models.CharField(max_length=250, verbose_name='前提条件')),
                ('method', models.CharField(max_length=20, verbose_name='请求方式')),
                ('execution_result', models.CharField(blank=True, max_length=200, null=True, verbose_name='执行结果')),
                ('note', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('executor', models.TextField(blank=True, null=True, verbose_name='执行人')),
            ],
            options={
                'verbose_name': '用例管理',
                'verbose_name_plural': '功能用例管理',
            },
        ),
        migrations.CreateModel(
            name='FunctionCaseChild',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('steps', models.CharField(max_length=999, verbose_name='操作步骤')),
                ('expected_results', models.CharField(max_length=100, verbose_name='预期结果')),
                ('parent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApiTest.FunctionCase', verbose_name='父id')),
            ],
        ),
    ]
