# Generated by Django 3.0.5 on 2020-05-29 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiTest', '0034_remove_functioncase_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='functioncase',
            name='area',
        ),
        migrations.AddField(
            model_name='functioncase',
            name='belong',
            field=models.CharField(default=1, max_length=50, verbose_name='所属区域'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='functioncase',
            name='execution_result',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='执行结果'),
        ),
        migrations.AlterField(
            model_name='functioncase',
            name='function_model',
            field=models.CharField(max_length=50, verbose_name='功能模块'),
        ),
        migrations.AlterField(
            model_name='functioncasechild',
            name='expected_results',
            field=models.CharField(max_length=999, verbose_name='预期结果'),
        ),
    ]
