# Generated by Django 3.0.5 on 2020-05-31 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiTest', '0037_auto_20200530_0011'),
    ]

    operations = [
        migrations.AddField(
            model_name='functioncase',
            name='system',
            field=models.CharField(default='erms', max_length=50, verbose_name='所属系统'),
            preserve_default=False,
        ),
    ]
