# Generated by Django 3.0.5 on 2020-05-31 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiTest', '0038_functioncase_system'),
    ]

    operations = [
        migrations.CreateModel(
            name='Head',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50, verbose_name='用户名')),
                ('phone', models.CharField(max_length=11, verbose_name='手机号')),
            ],
        ),
    ]
